### ISSUE TITLE
failed to import CPU

### ISSUE THREAD

**Issue by redwulftech** [uzumaxy/pyspectator#1]
I just installed pypectator on Kali rolling, no error during install. But, I'm unable to import CPU or use even the sample code. I've tried variations of import processor/ import pyspectator and lower case and uppercase on CPU, nothing seems to work.

**Comment by uzumaxy** [comment]
@redwulftech Thanks for this bug report. I've fixed this problem in the new 1.1.0 version. Can you please update package to version 1.1.0 and check how it works? Please note, that `CPU` class in new release was renamed to `Cpu`.

**Comment by uzumaxy** [comment]
Fixed.
